"""created nullable for phone_number

Revision ID: 8c2283c7018d
Revises: d9ff0ab46bd9
Create Date: 2024-10-20 19:12:12.659898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2283c7018d'
down_revision: Union[str, None] = 'd9ff0ab46bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
